# Generated by Django 6.0.2 on 2026-02-04 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srsapp", "0003_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjects",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="srsapp.course",
            ),
        ),
    ]
