# Generated by Django 6.0.2 on 2026-02-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srsapp", "0005_alter_subjects_course_id_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="roll_number",
            field=models.IntegerField(default=0),
        ),
    ]
