# Generated by Django 6.0.2 on 2026-02-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srsapp", "0006_student_roll_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="nation",
            field=models.CharField(default="True", max_length=250),
        ),
    ]
