# Generated by Django 6.0.2 on 2026-02-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srsapp", "0007_student_nation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="coursefullname",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="course",
            name="courseshortname",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="board1",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="board2",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="category",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="city",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="class1",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="class2",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="country",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="fname",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="gname",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="income",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="lname",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="mname",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="mobno",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="nation",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="ocp",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="ph",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="pyear1",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="pyear2",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll1",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll2",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="session",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="state",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="sub1",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="subjects",
            name="subject1",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="subjects",
            name="subject2",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="subjects",
            name="subject3",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="subjects",
            name="subject4",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="subjects",
            name="subject5",
            field=models.CharField(default="", max_length=250),
        ),
    ]
