# Generated by Django 6.0.2 on 2026-02-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srsapp", "0008_alter_course_coursefullname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="sub2",
            field=models.CharField(default="", max_length=250),
        ),
    ]
